#cloud-config
package_update: true
package_upgrade: true
packages:
  - qemu-kvm
  - libvirt
  - virt-install
  - bridge-utils
  - wget
  - unzip

runcmd:
  - systemctl enable --now libvirtd
  - usermod -aG libvirt ec2-user
  - |
    curl -L -o aqua-enforcer.zip "https://install.aquasec.com/releases/enforcer/v6.8.3/enforcer.zip"
    unzip aqua-enforcer.zip -d /opt/aqua
    chmod +x /opt/aqua/install.sh
    /opt/aqua/install.sh \
      --token "${aqua_enforcer_token}" \
      --gateway "${aqua_gateway}" \
      --host-type "linux" \
      --no-container-runtime
