#cloud-config
package_update: true
packages:
  - wget
  - curl

runcmd:
  - sudo dnf install -y wget curl
  - cd /opt
  - sudo wget https://get.aquasec.com/aquactl/stable/aquactl
  - sudo chmod +x aquactl
  - sudo ./aquactl deploy vm-enforcer --version 2022.4 --token fe69ae4 --gateway 1918-gw.cloud.aquasec.com:443
